CREATE TABLE ORDER_ITEM(
ORDER_ITEM_ID SERIAL PRIMARY KEY,
PRICE DECIMAL(10,2) NOT NULL,
QUANTITY INT NOT NULL,
ORDER_ID SERIAL,
PRODUCT_ID SERIAL,
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ,
FOREIGN KEY (ORDER_ID) REFERENCES ORDER (ORDER_ID)
);
