CREATE TABLE PRODUCT(
PRODUCT_ID SERIAL PRIMARY KEY,
NAME VARCHAR(150) NOT NULL,
DESCRIOTION TEXT,
PRICE DECIMAL(10,2) NOT NULL,
COLOR VARCHAR(50),
SIZE VARCHAR(50),
BRAND VARCHAR(150),
QUANTITY INT NOT NULL,
FOREIGN KEY (CATEGORY_ID) REFERENCES category (CATEGORY_ID) 
);
